"use client"
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import { useState } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [sidebar, setSidebar] = useState(false);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        <div className="min-h-screen max-w-screen-xl mx-auto flex xl:border-x-4 border-zinc-600 bg-zinc-800">

          { sidebar && <Sidebar /> }

          <nav className="fixed top-0 inset-x-0 w-full max-w-screen-xl mx-auto xl:px-[4px] z-50">
            <div className={`relative h-16 ${sidebar ? "ml-72" : ""} px-4 flex items-center justify-between bg-zinc-900`}> {/*ml-72 */}
              <Navbar setSidebar={setSidebar} />
            </div>
          </nav>

          <div className={`relative w-full ${sidebar ? "ml-72" : ""} mt-16 flex flex-col`}> {/*ml-72 */}
            <div className="h-full p-6 font-[family-name:var(--font-geist-sans)]">
              {children}
            </div>
          </div>

        </div>
      </body>
    </html>
  );
}
